//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPP1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bazadannihPPEntities2 : DbContext
    {
        public bazadannihPPEntities2()
            : base("name=bazadannihPPEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Igrokis> Igrokis { get; set; }
        public virtual DbSet<KomandiTurniri> KomandiTurniri { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Turniris> Turniris { get; set; }
    }
}
